# Generated by Django 5.2.5 on 2025-08-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utensil',
            name='description',
            field=models.TextField(default='No description'),
            preserve_default=False,
        ),
    ]
