# Generated by Django 5.2.5 on 2025-09-08 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='utensil',
            name='category',
            field=models.CharField(default='General', max_length=50),
        ),
    ]
